### ISSUE TITLE
Defining availability of accommodation

### ISSUE THREAD

**Issue by panicmilos** [ftrip-io/catalog-service#2]
Potrebno je omogućiti definisanje i izmenu termina kada je neki smeštaj dostupan. On se može rezervisati samo za vremenski interval kada je dostupan i nije već zauzet. Dostupnost smeštaja može se menjati za neki interval samo ako u njemu nema rezervacija.

**Comment by albertmakan** [comment]
With the merge of #9 and #13, we can consider this Issue as Done.
