### ISSUE TITLE
Defining pricing of accommodation

### ISSUE THREAD

**Issue by panicmilos** [ftrip-io/catalog-service#3]
Potrebno je omogućiti definisanje i izmenu cene smeštaja. Ona može biti promenjiva. Na primer ona može biti veća u letnjim mesecima, vikendom ili za vreme praznika. Omogućiti host-u da definiše ovakve razlike u ceni. Cena može da se zada po gostu ili po celoj smeštajnoj jedinici, a host bira jednu od te dve mogućnosti na nivou nekretnine. Cena se može menjati za neki interval samo ako u njemu nema rezervacija.

**Comment by albertmakan** [comment]
With the merge of #12, we can consider this Issue as Done.
