### ISSUE TITLE
Searching accommodation

### ISSUE THREAD

**Issue by panicmilos** [ftrip-io/catalog-service#4]
Smeštaj se pretražuje prema lokaciji, broju gostiju i datumu početka i kraja putovanja. Rezultati treba da obuhvate sve dostupne smeštaje u zadatom intervalu koji se nalaze na traženoj lokaciji i mogu primiti zadati broj gostiju. Pored osnovnih informacija, za svaku nekretninu treba da se prikaže ukupna cena smeštaja za sva noćenja, kao i jedinična cena (po osobi po noćenju ili po smeštaju po noćenju).

**Comment by draganaF** [comment]
With the merge of #15, we can consider this Issue as Done.
